### ISSUE TITLE
RisingStack Node.js Security Checklist

### ISSUE THREAD

**Issue by keith24** [Tracman-org/Server#121]
source: [blog.risingstack.com/node-js-security-checklist](https://blog.risingstack.com/node-js-security-checklist/)

- [ ] [Security HTTP Headers](https://blog.risingstack.com/node-js-security-checklist/#securityhttpheaders) ([tester](https://securityheaders.io/?q=https%3A%2F%2Fwww.tracman.org&followRedirects=on))
- [ ] [Brute Force Protection](https://blog.risingstack.com/node-js-security-checklist/#bruteforceprotection)
- [ ] [Session Management](https://blog.risingstack.com/node-js-security-checklist/#sessionmanagement)
- [ ] [CSRF](https://blog.risingstack.com/node-js-security-checklist/#csrf)
- [ ] [XSS](https://blog.risingstack.com/node-js-security-checklist/#xss)
- [ ] [Mongo injection](https://blog.risingstack.com/node-js-security-checklist/#sqlinjection)
- [ ] [SSL](https://blog.risingstack.com/node-js-security-checklist/#sslversionalgorithmskeylength)
- [ ] [HSTS](https://blog.risingstack.com/node-js-security-checklist/#hsts)
- [ ] [Account lockout](https://blog.risingstack.com/node-js-security-checklist/#accountlockout)
- [ ] [Regex DOS](https://blog.risingstack.com/node-js-security-checklist/#regularexpressions)
- [ ] [Node Security Project](https://blog.risingstack.com/node-js-security-checklist/#thenodesecurityproject)/[Synk](https://blog.risingstack.com/node-js-security-checklist/#snyk)
